import matter from "gray-matter";
import { DOCS_BY_PATH } from "./content";
import type { CategorySlug } from "./types";

export const FILENAME_RE = /^[a-z0-9]+(-[a-z0-9]+)*\.md$/;

export interface ParsedPreview {
  title: string;
  category: string;
  subcategory: string;
  tags: string[];
  updated: string;
  bodyPreview: string;
  autoGenerated: boolean;
}

export type ValidationResult =
  | { ok: true; parsed: ParsedPreview; finalContents: string }
  | { ok: false; error: string };

const REQUIRED_FIELDS = ["title", "category", "subcategory", "tags", "updated"] as const;

// "window-functions" -> "Window Functions"
function titleCaseFromSlug(slug: string): string {
  return slug
    .split("-")
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function todayIsoDate(): string {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function buildFrontmatter(
  category: CategorySlug,
  filename: string,
): { yaml: string; title: string; subcategory: string; updated: string } {
  const subcategory = filename.replace(/\.md$/, "");
  const title = titleCaseFromSlug(subcategory);
  const updated = todayIsoDate();
  const yaml =
    `---\n` +
    `title: "${title.replace(/"/g, '\\"')}"\n` +
    `category: "${category}"\n` +
    `subcategory: "${subcategory}"\n` +
    `tags: []\n` +
    `updated: "${updated}"\n` +
    `---\n\n`;
  return { yaml, title, subcategory, updated };
}

// Detects whether the raw file already starts with a YAML frontmatter block.
function hasFrontmatter(contents: string): boolean {
  const stripped = contents.replace(/^\uFEFF/, "");
  return /^---\s*\r?\n[\s\S]*?\r?\n---\s*(\r?\n|$)/.test(stripped);
}

export function validateUpload(
  selectedCategory: CategorySlug,
  filename: string,
  contents: string,
): ValidationResult {
  if (!FILENAME_RE.test(filename)) {
    return {
      ok: false,
      error: "Filename must be lowercase kebab-case, e.g. `window-functions.md`",
    };
  }

  // Auto-generate frontmatter when the file doesn't have one.
  let autoGenerated = false;
  let finalContents = contents.replace(/^\uFEFF/, "");
  if (!hasFrontmatter(finalContents)) {
    const { yaml } = buildFrontmatter(selectedCategory, filename);
    // Strip leading blank lines from the body so the doc starts cleanly.
    const body = finalContents.replace(/^\s*\n+/, "");
    finalContents = yaml + body;
    autoGenerated = true;
  }

  let parsed;
  try {
    parsed = matter(finalContents);
  } catch (e) {
    return { ok: false, error: `Could not parse YAML frontmatter: ${(e as Error).message}` };
  }

  const fm = parsed.data as Record<string, unknown>;
  const missing: string[] = [];
  for (const f of REQUIRED_FIELDS) {
    if (fm[f] === undefined || fm[f] === null || fm[f] === "") missing.push(f);
  }
  if (missing.length > 0) {
    return {
      ok: false,
      error: `Frontmatter is missing required field${missing.length > 1 ? "s" : ""}: ${missing.join(", ")}`,
    };
  }

  if (!Array.isArray(fm.tags)) {
    return { ok: false, error: "Frontmatter `tags` must be a YAML list (e.g. `[\"foo\", \"bar\"]`)" };
  }

  const fileSlug = filename.replace(/\.md$/, "");

  if (fm.category !== selectedCategory) {
    return {
      ok: false,
      error: `Frontmatter category "${String(fm.category)}" does not match selected category "${selectedCategory}"`,
    };
  }
  if (fm.subcategory !== fileSlug) {
    return {
      ok: false,
      error: `Frontmatter subcategory "${String(fm.subcategory)}" does not match filename "${fileSlug}"`,
    };
  }

  const targetPath = `/${selectedCategory}/${fileSlug}`;
  if (DOCS_BY_PATH.has(targetPath)) {
    return {
      ok: false,
      error: `A file with this name already exists in ${selectedCategory}`,
    };
  }

  const bodyPreview = parsed.content
    .replace(/\r\n/g, "\n")
    .split("\n")
    .slice(0, 6)
    .join("\n");

  return {
    ok: true,
    finalContents,
    parsed: {
      title: String(fm.title),
      category: String(fm.category),
      subcategory: String(fm.subcategory),
      tags: (fm.tags as string[]) ?? [],
      updated: String(fm.updated),
      bodyPreview,
      autoGenerated,
    },
  };
}

export interface UploadResponse {
  ok: boolean;
  path?: string;
  error?: string;
}

export async function uploadFile(
  category: CategorySlug,
  filename: string,
  contents: string,
): Promise<UploadResponse> {
  try {
    const res = await fetch("/__upload", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ category, filename, contents }),
    });
    const json = (await res.json()) as UploadResponse;
    return json;
  } catch (e) {
    return { ok: false, error: (e as Error).message };
  }
}
